window.quotes = [
    'npm install -g ember-cli',
    'git status',
    'Array(16).join({} - 1) + " Batman!"',
    'ember serve --live-reload',
    'composer install',
    'npm install',
    'bower install',
    'I actually took the time to write this',
    'I don\'t drink coffee',
    'Not a huge Microsoft fan',
    'A bit of a musician',
    'Don\'t worry, I don\'t byte',
    'Linux master race !',
    'Use the -f Luke',
    'It\'s finished, just need to test',
    'Probably not good looking in IE8',
    'Hmmmm, pizza',
    'Marylou ♥',
    '!important stuff',
    'Probably coding at the moment',
    'oh-my-zsh',
    'Do, or do not. There is no try.',
    'Woooo ! It\'s working !',
    'Was that feature really necessary ?',
    'You are a wizard Harry.',
    ':(){ :|: & };:',
    'There\'s no places like 127.0.0.1',
    'Pascal\'); DROP TABLE Users;--',
    'sudo apt-get upgrade',
    'ls -lah ~',
    'cd ..',
    'sudo rm -rf /',
    'Yeah, it will be done by tomorrow',
    'Somebody is watching you',
    '3.14159265359',
    'git blame',
    'ping google.com'
];
